pipeline{
    agent any
    stages{
        stage("Build Docker Image"){
            steps{
                script {
                    dockerapp = docker.build("marciocazevedo/kube-news:v${env.BUILD_ID}", '-f ./src/Dockerfile ./src')
                }
            }
        }
        stage("Push Docker Image"){
            steps{
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'DockerHub') {
                        dockerapp.push('latest')
                        dockerapp.push("v${env.BUILD_ID}")
                    }                
                }
            }
        }
        stage("Deploy Kubernetes"){
            steps{
                withKubeConfig([credentialsId: 'kubeconfig']) {
                    sh 'kubectl apply -f ./src/deployment.yaml'
                }
            }
        }
    }
}
